Add Bundler CVE-2020-36327
rubysec/ruby-advisory-db pull request #468
Opened 2021-04-30 07:59 UTC by zofrex

PR to add the CVE for implicit dependency confusion.

I have two questions about this:

1) Is it correct to put 2.2.10 in the `unaffected_versions` section? Technically that version was patched (and the patch was rolled back in 2.2.11), so `patched_versions` seems more appropriate. However, if I put it there then a test fails:

```
Failures:

  1) gems /Users/zofrex/Code/ruby/ruby-advisory-db/spec/../gems/bundler/CVE-2020-36327.yml versions assumes that future versions will be patched
     Failure/Error: expect(versions.last.match(/^>=|^>/)).to be_truthy
     
       expected: truthy value
            got: nil
     Shared Example Group: "Gem Advisory" called from ./spec/advisories_spec.rb:8
     # ./spec/gem_example.rb:32:in `block (4 levels) in <top (required)>'
```

2) I wrote a blog post about this vulnerability, explaining it in more detail and outlining some possible mitigations. Would it be OK to add the URL to the related section? I've left it out to start with in case self-promotion isn't ok.

2021-05-12 19:07 UTC, zofrex commented on gems/bundler/CVE-2020-36327.yml
> +patched_versions:
It was fixed in 2.2.10 but the fix was rolled back in 2.2.11. It remains unfixed in 2.2.17.

2021-05-12 19:07 UTC, zofrex commented on gems/bundler/CVE-2020-36327.yml
> +unaffected_versions:
The bug was introduced in 1.16.0 so I think that part is correct at least.

2021-05-12 19:08 UTC, zofrex commented on gems/bundler/CVE-2020-36327.yml
> +url: https://nvd.nist.gov/vuln/detail/CVE-2020-36327
I agree, that's the best option here. Good call!

2021-05-12 19:08 UTC, zofrex commented
> So, 2.2.10 and 2.2.17 are both fixed? I'm just a bit confused about what versions have the fix in them.

Just 2.2.10 is fixed.

2021-05-24 18:47 UTC, reedloden commented
Are there plans for Bundler to fix this? I'm a bit hesitant to just add an entry that basically tells everybody to just install only Bundler v2.2.10, when the Bundler team reverted https://github.com/rubygems/rubygems/pull/4385 and still hasn't fixed it yet. Seems like https://github.com/rubygems/rubygems/pull/4381 may be a partial fix for this that was included in v2.2.14?

@deivid-rodriguez can you help here? Is this CVE fully addressed in some prior Bundler release after v2.2.10?

2021-05-24 19:22 UTC, deivid-rodriguez commented
We will release a fix for this imminently as bundler 2.2.18.

2021-05-24 19:44 UTC, reedloden requested changes
I don't want to merge this until the fixed version of bundler is released, but let's just make sure it's ready to go before then.

2021-05-24 19:44 UTC, reedloden commented on gems/bundler/CVE-2020-36327.yml
> +  - "2.2.10"
Move to `patched_versions`

2021-05-24 19:44 UTC, reedloden commented on gems/bundler/CVE-2020-36327.yml
> +patched_versions:
Let's add `>= 2.2.18` in advance of the fixed bundler version.

2021-05-24 19:44 UTC, reedloden commented on gems/bundler/CVE-2020-36327.yml
> +  Bundler 1.16.0 through 2.2.9 and 2.2.11 through 2.2.16 sometimes chooses a
Change 2.2.16 to 2.2.17. Looks like 2.2.18 will be the fixed version.

2021-05-24 19:54 UTC, reedloden commented
Looks like GitHub released a security advisory for this as well.

So, let's add `ghsa: fp4w-jxhp-m23p` and `cvss_v3: 8.8`.

2021-05-24 21:59 UTC, zofrex commented
Happy to make the requested changes as and when the time is right, but I must disagree with waiting to merge this until a fix is out.

> I'm a bit hesitant to just add an entry that basically tells everybody to just install only Bundler v2.2.10

Really what this entry does is tell people "you might be vulnerable to this bug, and if you are, here are your options". I am definitely hesitant to push people towards 2.2.10 because that did have a lot of issues, but there are also several mitigations outlined in the links in this entry.

In my opinion an advisory without a patch is still hugely valuable to users because it lets us know there might be an issue, we can then look into whether or not it affects us, and if it does, make a decision about whether our personal risk exposure is high enough to apply one of the mitigations while we wait for the patch.

This isn't a hugely unusual scenario, advisories coming out with no patch happens from time to time, and I'd rather know about it than not. In extreme cases I have taken systems offline or avoided using them, in others applied a mitigation, and in others, crossed my fingers, but that's a decision that users can only make for themselves, and a decision that is best guided by having all the available information in front of them.

For that reason I strongly urge you to merge this as soon as possible. We can update it as the situation changes.

2021-05-24 22:06 UTC, zofrex commented on gems/bundler/CVE-2020-36327.yml
> +  - "2.2.10"
I don't think < 1.16.0 is "patched" because that predates the vulnerability being introduced? 2.2.10 is but, as discussed above, that breaks the tests.

2021-05-24 22:07 UTC, zofrex commented on gems/bundler/CVE-2020-36327.yml
> +  Bundler 1.16.0 through 2.2.9 and 2.2.11 through 2.2.16 sometimes chooses a
Let's add ">= 2.2.18" when that's confirmed.

2021-05-25 00:10 UTC, reedloden commented on gems/bundler/CVE-2020-36327.yml
> +  - "2.2.10"
I made a change, so I think the tests will work now.

2021-05-25 00:11 UTC, reedloden approved these changes

2021-05-25 19:02 UTC, deivid-rodriguez commented
Bundler 2.2.18 has been released.

2021-05-25 21:37 UTC, zofrex commented
Rebased and squashed, as I think this is ready to go now.

2021-05-25 23:30 UTC, merged

2021-05-25 23:32 UTC, phillmv commented
Merged! Thank you all for your work. If need be, fwiw, we can also find a way to have better sync/coordination with GitHub advisories.