Added rubies/ruby/CVE-2017-17790.yml
rubysec/ruby-advisory-db pull request #558
Opened 2023-03-20 21:20 UTC by jasnow

See if I have fixed my branching issues.

Adding a single file, rubies/ruby/CVE-2017-17790.yml file.

It is related to issue #438.

Feel free to edit the file. Some of the text came from the GHSA database.

2023-03-20 21:24 UTC, jasnow commented
Verified all green checks.

2023-03-21 16:37 UTC, postmodern requested changes
Minor changes requested.

2023-03-21 16:37 UTC, postmodern commented on rubies/ruby/CVE-2017-17790.yml
> +  "The lazy_initialize function in lib/resolv.rb in Ruby through 2.4.3
Can remove the lone double quote.

2023-03-21 16:37 UTC, postmodern commented on rubies/ruby/CVE-2017-17790.yml
> +title: The lazy_initialize function in lib/resolv.rb in Ruby...
Can probably remove the `...` from the title.

2023-03-21 16:37 UTC, postmodern commented on rubies/ruby/CVE-2017-17790.yml
> + - '>= 2.2.8'
Should be `~> 2.2.8` so the version ranges don't overlap.

2023-03-21 16:37 UTC, postmodern commented on rubies/ruby/CVE-2017-17790.yml
> + - '>= 2.3.5'
Should be `~> 2.3.5` so the version ranges don't overlap.

2023-03-21 17:28 UTC, jasnow commented
Think I fixed all feedback.

2023-03-21 18:52 UTC, merged

2023-03-21 18:57 UTC, jasnow commented
Think #438 is done.