2 new and 6 modified ruby advisories
rubysec/ruby-advisory-db pull request #591
Opened 2023-05-03 18:35 UTC by jasnow

2 new and 6 modified (my new approach) rubies/ruby advisories based on GHSA and ruby-advisory-db data.

yamllint and "rake" are green.

5 files did not make the cut.

2023-05-03 23:16 UTC, postmodern requested changes
Noticed a few unnecessary changes.

2023-05-03 23:16 UTC, postmodern commented on rubies/ruby/CVE-2015-1855.yml
> + - '>= 2.2.2'
I thought we were standardizing on double-quotes for version ranges? Why single-quotes for these?

2023-05-03 23:16 UTC, postmodern commented on rubies/ruby/CVE-2019-16255.yml
> +title: 'A code injection vulnerability of Shell#[] and Shell#test'
It doesn't appear that single-quotes are needed here:

```ruby
>> YAML.load("title: A code injection vulnerability of Shell#[] and Shell#tes
t\n")
=> {"title"=>"A code injection vulnerability of Shell#[] and Shell#test"}
```

2023-05-03 23:16 UTC, postmodern commented on rubies/ruby/CVE-2015-1855.yml
> +url: https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability
It appears that `https://www.ruby-lang.org/` will redirect `https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability` back to `https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability/`. Better to keep using the canonical URL.

2023-05-03 23:33 UTC, jasnow commented on rubies/ruby/CVE-2019-16255.yml
> +title: 'A code injection vulnerability of Shell#[] and Shell#test'
will fix ; worried about []

2023-05-03 23:34 UTC, jasnow commented on rubies/ruby/CVE-2015-1855.yml
> +url: https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability
both work

2023-05-03 23:35 UTC, jasnow commented on rubies/ruby/CVE-2015-1855.yml
> +url: https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability
will fix

2023-05-04 00:10 UTC, jasnow commented on rubies/ruby/CVE-2015-1855.yml
> + - '>= 2.2.2'
sync script does double-quotes and I see single-quotes and no quotes in the repo, so I pick singles.

2023-05-04 00:18 UTC, postmodern commented
Cherry-picked 67b3c87 into master as a separate commit.

2023-05-04 11:43 UTC, closed without merging