Updating advisories with osvdb.org in "url:" field
rubysec/ruby-advisory-db pull request #613
Opened 2023-05-31 16:16 UTC by jasnow

## Updating advisories with osvdb.org in "url:" field

  * Updated "url:" field with non-osvdb reference since     osvdb.org is no longer available.
  * Added "ghsa:" field value for advisories with "cve:" values.
  * Added "related:" references as evidence for further work (for advisories with "cve": values, usually only 4 refs; check NVD reference for full list).
  * Changed quotes to or adding double-quotes as needed.
  * Added "notes:" as needed to be more explicit.
  * Line wrapped text fields as needed.
  * Merged one duplicate OSVDB-78119 advisory into CVE-2012-5372 advisory.

## Special Notes
 * No new files/advisories in this PR.
 * Will delete rubies/rbx/OSVDB-78119.yml file in separate PR.

## Checks
 * internal "morechks" script (all clean)
 * yamlint (green)
 * rake (green)

2023-06-02 02:07 UTC, postmodern requested changes
The primary `url:` should ideally point to a web page with the advisory information, that explains the impact. how to upgrade, etc. It's probably not very user-friendly to link to raw GitHub code or commit diffs. If no other suitable URL exists for the advisory, perhaps we could link to the https://rubysec.com page for the advisory?

2023-06-02 11:22 UTC, jasnow commented
> The primary `url:` should ideally point to a web page with the advisory information, that explains the impact. how to upgrade, etc. It's probably not very user-friendly to link to raw GitHub code or commit diffs. If no other suitable URL exists for the advisory, perhaps we could link to the https://rubysec.com page for the advisory?

 I agree that sometimes is was hard to find the right one for the main "url:" field.  My approach in picking the main "url:" was to pick the public announcement of the vulnerability by the project if possible or proof that the vulnerability was real. I will review your feedback and try to improve my selection.

2023-06-02 13:56 UTC, jasnow commented on gems/dragonfly/OSVDB-110439.yml
> +    - https://security.snyk.io/vuln/SNYK-RUBY-DRAGONFLY-20193
done

2023-06-02 13:57 UTC, jasnow commented on gems/dragonfly/OSVDB-97854.yml
> +url: https://github.com/markevans/dragonfly/blob/master/spec/dragonfly/shell_spec.rb#L26
done

2023-06-02 13:57 UTC, jasnow commented on gems/flavour_saver/OSVDB-110796.yml
> +url: https://github.com/FlavourSaver/FlavourSaver/compare/v0.3.2...v0.3.3
done

2023-06-02 13:58 UTC, jasnow commented on gems/fog-dragonfly/OSVDB-97854.yml
> +url: https://github.com/markevans/dragonfly/blob/master/spec/dragonfly/shell_spec.rb#L26
done

2023-06-02 14:00 UTC, jasnow commented on gems/jruby-sandbox/OSVDB-106279.yml
> +url: https://www.exploit-db.com/exploits/33028
done

2023-06-02 14:01 UTC, jasnow commented on gems/loofah/OSVDB-90945.yml
> +url: https://github.com/flavorjones/loofah/compare/v0.4.5...v0.4.6
done

2023-06-02 14:05 UTC, jasnow commented on gems/fog-dragonfly/OSVDB-110439.yml
> +url: https://github.com/markevans/dragonfly/compare/v0.8.3...v0.8.4
done

2023-06-02 14:07 UTC, jasnow commented on gems/web-console/OSVDB-112346.yml
> +url: https://github.com/rails/web-console/compare/v2.0.0.beta3...v2.0.0.beta4
done

2023-06-02 14:08 UTC, jasnow commented on gems/handlebars-source/OSVDB-131671.yml
> +url: https://github.com/handlebars-lang/handlebars.js/compare/v3.0.8...v4.0.0
done

2023-06-02 15:33 UTC, jasnow commented
Found 2 more files needs similar changes.

2023-06-03 02:52 UTC, postmodern approved these changes
LGTM

2023-06-03 02:53 UTC, merged

2023-06-03 11:10 UTC, jasnow commented
Thanks