Added 2016 gems/bundler/CVE-2016-7954.yml advisory
rubysec/ruby-advisory-db pull request #643
Opened 2023-06-21 16:27 UTC by jasnow

Added 2016 gems/bundler/CVE-2016-7954.yml advisory.

NOTE: This will flag all 1.x versions of bundler.

2023-06-22 17:30 UTC, postmodern commented
@indirect while I agree with you this is one of those vulnerabilities that requires a specific scenario to trigger, it is still a vulnerability and got a CVE. Also, Bundler 2.x has been out for a while, so maybe the annoyance of flagging Bundler 1.x as vulnerable might not be that bad? Also, why couldn't a patch be backported to Bundler 1.x? Unfortunately this is kind of what happens when a patch isn't backported, the whole previous version range has to be considered vulnerable.

@jasnow what do you think about adding an extra paragraph to the description, emphasizing that this vulnerability requires two `source`s be set in the `Gemfile`, otherwise users can safely ignore the vulnerability?

2023-06-22 17:37 UTC, jasnow commented
> @indirect while I agree with you this is one of those vulnerabilities that requires a specific scenario to trigger, it is still a vulnerability and got a CVE. Also, Bundler 2.x has been out for a while, so maybe the annoyance of flagging Bundler 1.x as vulnerable might not be that bad? Also, why couldn't a patch be backported to Bundler 1.x? Unfortunately this is kind of what happens when a patch isn't backported, the whole previous version range has to be considered vulnerable.
> 
> @jasnow what do you think about adding an extra paragraph to the description, emphasizing that this vulnerability requires two `source`s be set in the `Gemfile`, otherwise users can safely ignore the vulnerability?

Sure

2023-06-22 17:47 UTC, jasnow commented
What's a global source vs. "source 'https://rubygems.org' "?

2023-06-22 17:59 UTC, jasnow commented
"global source" defined here: https://bundler.io/v2.4/man/gemfile.5.html

2023-06-23 06:25 UTC, postmodern requested changes
Wording changes.

2023-06-23 06:25 UTC, postmodern commented on gems/bundler/CVE-2016-7954.yml
>    NOTE: This might overlap CVE-2013-0334.
I think that should be a `note: ` attribute and not part of the `description:` text.

2023-06-23 06:25 UTC, postmodern commented on gems/bundler/CVE-2016-7954.yml
> +  *****************************************************************'
No need for the asterisks, just a simple `Note: ` should suffice.

2023-06-23 06:25 UTC, postmodern commented on gems/bundler/CVE-2016-7954.yml
> +  *****************************************************************'
Maybe also explicitly mention that if the user's `Gemfile` does not use multiple sources, the vulnerability can be ignored.

2023-06-23 06:34 UTC, jasnow commented on gems/bundler/CVE-2016-7954.yml
>    NOTE: This might overlap CVE-2013-0334.
Fixed

2023-06-23 06:35 UTC, jasnow commented on gems/bundler/CVE-2016-7954.yml
> +  *****************************************************************'
Removed asterisks.

2023-06-23 06:35 UTC, jasnow commented on gems/bundler/CVE-2016-7954.yml
> +  *****************************************************************'
Added text

2023-06-23 15:36 UTC, postmodern approved these changes

2023-06-23 15:37 UTC, merged

2023-06-23 15:47 UTC, jasnow commented
Thanks