6 new GHSA sync'ed advisories
rubysec/ruby-advisory-db pull request #677
Opened 2023-07-06 17:06 UTC by jasnow

6 new GHSA sync'ed advisories

2023-07-06 22:56 UTC, postmodern requested changes
Noticed some discrepencies between the `description` `Solution`/`Recommendation` instructions and the `patched_versions:`. That will probably confuse end-users.

2023-07-06 22:56 UTC, postmodern commented on gems/grpc/CVE-2023-32731.yml
> +  - ">= 1.53.0"
The NVD entry says versions `>= 1.53.0, < 1.55.0` are effected. Not sure where they are getting `1.53.0` from, but I think patched versions should be `>= 1.55.0`.

2023-07-06 22:56 UTC, postmodern commented on gems/jquery-rails/CVE-2012-6708.yml
> +  Update to version 1.9.0 or later.
The description text is from the jQuery CVE. The version number should reflect `jquery-rails`, which has different version numbers than upstream jQuery.

2023-07-06 22:56 UTC, postmodern commented on gems/jquery-rails/CVE-2015-9251.yml
> +  Update to version 3.0.0 or later.
Same here, text is from the jQuery CVE and mentions a different version from `jquery-rails`.

2023-07-06 22:56 UTC, postmodern commented on gems/jquery-rails/CVE-2020-7656.yml
> +  Upgrade to version 1.9.0 or later.
and here as well.

2023-07-06 22:56 UTC, postmodern commented on gems/nokogiri/CVE-2021-3537.yml
> +url: https://bugzilla.redhat.com/show_bug.cgi?id=1956522
Maybe the primary URL should be `https://github.com/advisories/GHSA-286v-pcf5-25rc` which discusses nokogiri specifically.

2023-07-06 22:56 UTC, postmodern commented on gems/nokogiri/CVE-2021-3518.yml
> +url: https://bugzilla.redhat.com/show_bug.cgi?id=1954242
Maybe the primary URL should be `https://github.com/advisories/GHSA-v4f8-2847-rwm7` which discusses nokogiri specifically.

2023-07-06 23:13 UTC, jasnow commented
With all of the issues with my PR, I think a REDO is in order. Thanks for your thoughtful feedback.

2023-07-06 23:13 UTC, closed without merging

2023-07-07 00:21 UTC, jasnow commented on gems/grpc/CVE-2023-32731.yml
> +  - ">= 1.53.0"
redo found that 1.53.1 was the right answer

2023-07-07 00:35 UTC, postmodern commented
You can always `git commit --amend` and `git push origin master -f`.