GHSA Sync: Added/updated 3 new advisories
rubysec/ruby-advisory-db pull request #690
Opened 2023-07-29 14:31 UTC by jasnow

GHSA Sync: Added/updated 3 new advisories.

2023-07-29 21:24 UTC, postmodern requested changes
Missing `patched_version` on one.

2023-07-29 21:24 UTC, postmodern commented on gems/logstash-core/CVE-2016-10362.yml
> +notes: Never patched
The description says "Prior to Logstash version 5.0.1" and `logstash-core` is now on [version 7.5.2](https://rubygems.org/gems/logstash-core), so I think `patched_versions` should be `>= 5.0.1`.

2023-07-30 00:30 UTC, jasnow commented on gems/logstash-core/CVE-2016-10362.yml
> +notes: Never patched
Made fix.

2023-07-30 01:08 UTC, postmodern approved these changes

2023-07-30 01:09 UTC, merged