GHSA Sync: Added 1 brand new advisory
rubysec/ruby-advisory-db pull request #705
Opened 2023-09-15 11:00 UTC by jasnow

GHSA Sync: Added 1 brand new advisory: gems/sidekiq/CVE-2023-26141.yml

2023-09-15 15:55 UTC, postmodern requested changes

2023-09-15 15:55 UTC, postmodern commented on gems/sidekiq/CVE-2023-26141.yml
> +url: https://github.com/sidekiq/sidekiq/blob/main/Changes.md#713
I would just recommend using an NVD or GHSA link to the actual advisory information.

2023-09-15 16:12 UTC, jasnow commented on gems/sidekiq/CVE-2023-26141.yml
> +url: https://github.com/sidekiq/sidekiq/blob/main/Changes.md#713
You will always see that I use the first public notice from the actual project for  url: if at all possible.

2023-09-16 02:20 UTC, closed without merging

2023-09-16 02:20 UTC, postmodern commented
Manually cherry-picked 2e93e5b8994906bfb3c8fc6a4a7112058c4b3982 and changed the URL in 6bafd6d492bef2187cb39279befce0cba4283ea9.