CVE 2019-19919 for bootstrap-wysihtml5-rails
rubysec/ruby-advisory-db pull request #719
Opened 2023-11-22 22:55 UTC by ddalcino

Fix #718

Please let me know if you need anything else. Thanks!

2023-11-22 23:26 UTC, ddalcino commented on gems/bootstrap-wysihtml5-rails/CVE-2019-19919.yml
> +gem: bootstrap-wysihtml5-rails
```suggestion
---
gem: bootstrap-wysihtml5-rails
```

2023-11-23 00:59 UTC, postmodern requested changes
Probably needs `unaffected_versions:` attribute.

2023-11-23 00:59 UTC, postmodern commented on gems/bootstrap-wysihtml5-rails/CVE-2019-19919.yml
> +  Not affected: < 0.3.3.5
If there are un-affected versions of the gem, than there should be an `unaffected_versions:` attribute with the version range.

2023-11-23 10:12 UTC, postmodern requested changes
`unaffected_versions:` needs to be an Array.

2023-11-23 10:12 UTC, postmodern commented on gems/bootstrap-wysihtml5-rails/CVE-2019-19919.yml
> +unaffected_versions: "< 0.3.3.5"
Needs to be an Array value.

2023-11-23 19:09 UTC, postmodern approved these changes

2023-11-23 19:10 UTC, merged